2023-12-25 16:59:15,728 INFO shopapp.views: Rendering shop index
2023-12-25 16:59:16,090 INFO shopapp.views: Rendering shop index
2023-12-25 16:59:16,522 INFO shopapp.views: Rendering shop index
2023-12-25 17:02:16,225 INFO django.utils.autoreload: /home/vysnik/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2023-12-25 17:02:16,652 INFO django.utils.autoreload: Watching for file changes with StatReloader
2023-12-27 16:39:18,688 INFO django.utils.autoreload: Watching for file changes with StatReloader
2023-12-27 16:39:30,204 WARNING django.request: Not Found: /
2023-12-27 16:39:40,342 WARNING django.request: Not Found: /__debug__/
2023-12-27 16:39:42,594 WARNING django.request: Not Found: /__debug__/
2023-12-27 16:39:45,414 WARNING django.request: Not Found: /__debug__
2023-12-30 17:39:16,154 INFO django.utils.autoreload: Watching for file changes with StatReloader
2023-12-30 17:39:35,987 WARNING django.request: Not Found: /
2023-12-30 17:39:35,992 WARNING django.request: Not Found: /
2023-12-30 17:39:37,684 WARNING django.request: Not Found: /favicon.ico
2023-12-30 17:39:38,397 WARNING django.request: Not Found: /
2023-12-30 17:39:49,237 INFO shopapp.views: Rendering shop index
2023-12-30 17:39:49,484 WARNING django.request: Not Found: /favicon.ico
2023-12-31 09:24:13,822 INFO django.utils.autoreload: Watching for file changes with StatReloader
2023-12-31 09:24:27,792 WARNING django.request: Not Found: /
2023-12-31 09:24:34,579 INFO shopapp.views: Rendering shop index
2024-01-01 12:12:44,947 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-01 12:12:59,797 WARNING django.request: Not Found: /
2024-01-01 12:16:31,627 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-01 12:16:34,893 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-01 12:17:18,127 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-01 12:17:18,924 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-01 12:17:20,170 ERROR django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 238, in get
    name = elem["nae"]
KeyError: 'nae'
2024-01-01 12:31:58,158 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2024-01-01 12:31:59,316 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-01 12:32:11,273 ERROR django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 238, in get
    name = elem["nae"]
KeyError: 'nae'
2024-01-01 12:34:13,819 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-01 12:34:14,392 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-04 16:36:21,049 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-04 16:36:36,214 WARNING django.request: Not Found: /
2024-01-04 16:37:12,211 WARNING django.request: Not Found: /favicon.ico
2024-01-04 16:37:29,120 WARNING django.request: Not Found: /favicon.ico
2024-01-04 16:46:05,519 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2024-01-04 16:46:08,767 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-04 16:46:11,117 ERROR django.request: Internal Server Error: /en/admin/shopapp/product/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_modify.py", line 65, in submit_row
    add = context["add"]
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'add'
2024-01-04 16:46:42,123 WARNING django.request: Not Found: /favicon.ico
2024-01-04 17:06:37,082 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2024-01-04 17:06:41,621 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-04 17:06:43,520 WARNING django.request: Not Found: /favicon.ico
2024-01-04 17:07:13,459 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2024-01-04 17:07:14,455 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-04 17:09:04,364 ERROR django.request: Internal Server Error: /en/admin/shopapp/product/import_products_csv/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: shopapp_product.created_by_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/admin.py", line 95, in import_csv
    Product.objects.bulk_create(products)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 803, in bulk_create
    returned_columns = self._batched_insert(
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1831, in _batched_insert
    self._insert(
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 641, in execute
    result = real_execute(self, sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: shopapp_product.created_by_id
2024-01-04 17:16:09,731 WARNING django.request: Not Found: /en/products
2024-01-04 17:16:15,481 INFO shopapp.views: Rendering shop index
2024-01-05 08:49:36,897 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-05 08:49:52,885 WARNING django.request: Not Found: /
2024-01-05 09:16:37,807 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-05 09:16:40,211 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-05 09:16:45,308 WARNING django.request: Not Found: /favicon.ico
2024-01-05 09:16:55,866 WARNING django.request: Method Not Allowed: /ru/shop/api/products/upload_csv/
2024-01-07 09:37:50,159 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-07 09:38:23,092 WARNING django.request: Not Found: /
2024-01-07 09:38:24,410 WARNING django.request: Not Found: /
2024-01-08 07:52:04,939 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 07:52:18,071 WARNING django.request: Not Found: /
2024-01-08 07:53:12,412 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2024-01-08 07:53:13,447 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 07:57:17,124 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/urls.py changed, reloading.
2024-01-08 07:57:18,986 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 07:57:19,408 WARNING django.request: Not Found: /blog/
2024-01-08 07:57:32,569 WARNING django.request: Not Found: /blog/articles/1/
2024-01-08 08:02:35,739 WARNING django.request: Not Found: /blog/articles/1/
2024-01-08 08:11:55,822 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2024-01-08 08:11:56,670 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 08:12:17,337 ERROR django.request: Internal Server Error: /blog/articles/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'article' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['blog/articles/(?P<pk>[0-9]+)/\\Z']
2024-01-08 08:12:18,863 ERROR django.request: Internal Server Error: /blog/articles/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'article' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['blog/articles/(?P<pk>[0-9]+)/\\Z']
2024-01-08 08:14:15,483 ERROR django.request: Internal Server Error: /blog/articles/3/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: blogapp/article_detail.html
2024-01-08 08:23:35,078 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/admin.py changed, reloading.
2024-01-08 08:23:36,166 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 08:24:19,059 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/admin.py changed, reloading.
2024-01-08 08:24:19,631 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 08:59:01,212 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/blogapp/views.py changed, reloading.
2024-01-08 08:59:02,734 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 09:11:13,386 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 16:13:56,980 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-08 16:14:15,917 WARNING django.request: Not Found: /
2024-01-08 16:14:32,799 ERROR django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: sitemap.xml
2024-01-08 16:16:15,013 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2024-01-08 16:16:16,968 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-09 16:54:09,805 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-09 16:54:28,357 WARNING django.request: Not Found: /
2024-01-11 13:07:16,081 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-11 13:07:20,025 WARNING django.request: Not Found: /
2024-01-11 13:07:23,790 WARNING django.request: Not Found: /favicon.ico
2024-01-11 15:08:33,325 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-11 15:08:47,748 WARNING django.request: Not Found: /
2024-01-11 15:15:10,922 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2024-01-11 15:15:14,472 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-11 15:17:52,030 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2024-01-11 15:17:53,348 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-12 11:27:32,905 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-12 11:27:36,682 WARNING django.request: Not Found: /
2024-01-12 11:27:37,543 WARNING django.request: Not Found: /favicon.ico
2024-01-12 11:40:01,582 INFO django.utils.autoreload: C:\Users\USER\PycharmProjects\python_django\mysite\shopapp\common.py changed, reloading.
2024-01-12 11:40:04,722 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-14 07:26:25,424 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-14 07:26:42,402 WARNING django.request: Not Found: /
2024-01-14 07:30:38,007 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/common.py changed, reloading.
2024-01-14 07:30:41,238 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-14 07:54:59,290 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-14 07:55:19,090 WARNING django.request: Not Found: /
2024-01-14 07:55:42,903 ERROR django.request: Internal Server Error: /ru/admin/shopapp/order/import_orders_csv/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/admin.py", line 134, in import_csv
    csv_file = save_csv_orders(
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/common.py", line 28, in save_csv_orders
    delivery_address=row['delivery_address'],
KeyError: 'delivery_address'
2024-01-14 07:56:11,765 WARNING django.request: Not Found: /
2024-01-14 07:57:19,350 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/common.py changed, reloading.
2024-01-14 07:57:21,879 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-14 07:58:00,759 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/common.py changed, reloading.
2024-01-14 07:58:01,547 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-14 07:58:06,616 ERROR django.request: Internal Server Error: /ru/admin/shopapp/order/import_orders_csv/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/admin.py", line 134, in import_csv
    csv_file = save_csv_orders(
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/common.py", line 28, in save_csv_orders
    delivery_address=row['delivery_address'],
KeyError: 'delivery_address'
2024-01-14 07:58:37,838 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/common.py changed, reloading.
2024-01-14 07:58:39,208 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-14 07:58:46,959 ERROR django.request: Internal Server Error: /ru/admin/shopapp/order/import_orders_csv/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/admin.py", line 134, in import_csv
    csv_file = save_csv_orders(
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/common.py", line 28, in save_csv_orders
    delivery_address=row['delivery_address'],
KeyError: 'delivery_address'
2024-01-14 07:59:47,398 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/common.py changed, reloading.
2024-01-14 07:59:50,791 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-16 16:00:41,138 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-16 16:00:58,128 WARNING django.request: Not Found: /
2024-01-16 16:01:08,502 INFO shopapp.views: Rendering shop index
2024-01-16 16:08:59,761 INFO shopapp.views: Rendering shop index
2024-01-16 16:09:13,384 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2024-01-16 16:09:15,176 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-16 16:09:40,660 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-16 16:10:54,029 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2024-01-16 16:10:54,647 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-16 16:10:59,232 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-20 14:18:17,976 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-20 14:18:32,616 WARNING django.request: Not Found: /
2024-01-20 14:18:34,162 WARNING django.request: Not Found: /favicon.ico
2024-01-20 14:18:58,649 INFO shopapp.views: Rendering shop index
2024-01-20 14:19:06,485 WARNING django.request: Not Found: /myauth
2024-01-20 14:19:29,498 WARNING django.request: Not Found: /myauth/cookir/get
2024-01-20 14:19:39,235 WARNING django.request: Not Found: /myauth/cookie/get
2024-01-20 14:20:45,018 WARNING django.request: Not Found: /myauth/hello
2024-01-20 14:23:28,272 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/mysite/urls.py changed, reloading.
2024-01-20 14:23:30,575 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-20 14:25:41,518 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/myauth/views.py changed, reloading.
2024-01-20 14:25:43,414 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-20 14:29:12,601 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/urls.py changed, reloading.
2024-01-20 14:29:13,186 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-20 14:29:17,151 INFO shopapp.views: Rendering shop index
2024-01-20 14:30:51,674 INFO shopapp.views: Rendering shop index
2024-01-20 14:38:21,562 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-20 14:38:24,182 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-20 14:40:33,739 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-21 16:59:28,957 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-21 16:59:44,207 WARNING django.request: Not Found: /
2024-01-21 17:01:10,628 INFO shopapp.views: Rendering shop index
2024-01-21 17:01:13,541 INFO shopapp.views: Rendering shop index
2024-01-21 17:01:14,425 INFO shopapp.views: Rendering shop index
2024-01-21 17:01:15,083 INFO shopapp.views: Rendering shop index
2024-01-21 17:02:27,298 INFO shopapp.views: Rendering shop index
2024-01-21 17:02:32,034 INFO shopapp.views: Rendering shop index
2024-01-21 17:02:33,046 INFO shopapp.views: Rendering shop index
2024-01-21 17:04:41,848 WARNING django.request: Not Found: /myauth
2024-01-21 17:04:50,311 ERROR django.request: Internal Server Error: /ru/myauth/about-me/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile-update' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['ru/myauth/profiles/(?P<pk>[0-9]+)/update/\\Z']
2024-01-21 17:04:56,955 WARNING django.request: Not Found: /ru/myauth/about_me/
2024-01-21 17:05:25,572 ERROR django.request: Internal Server Error: /ru/myauth/about-me/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile-update' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['ru/myauth/profiles/(?P<pk>[0-9]+)/update/\\Z']
2024-01-21 17:05:55,390 WARNING django.request: Not Found: /favicon.ico
2024-01-21 17:06:41,691 WARNING django.request: Not Found: /favicon.ico
2024-01-21 17:06:46,291 ERROR django.request: Internal Server Error: /ru/myauth/about-me/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile-update' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['ru/myauth/profiles/(?P<pk>[0-9]+)/update/\\Z']
2024-01-21 17:07:54,658 ERROR django.request: Internal Server Error: /ru/myauth/about-me/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile-update' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['ru/myauth/profiles/(?P<pk>[0-9]+)/update/\\Z']
2024-01-21 17:08:12,053 WARNING django.request: Not Found: /favicon.ico
2024-01-22 15:17:11,582 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-22 15:17:27,103 WARNING django.request: Not Found: /
2024-01-22 15:17:35,160 INFO shopapp.views: Rendering shop index
2024-01-22 15:29:05,406 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2024-01-22 15:29:07,520 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-27 14:20:12,059 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-27 14:21:04,243 WARNING django.request: Not Found: /
2024-01-27 15:10:55,512 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-27 15:11:03,141 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-27 15:22:57,020 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-27 15:23:00,407 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-27 15:35:17,897 WARNING django.request: Not Found: /users/1/orders/
2024-01-27 15:36:02,509 WARNING django.request: Not Found: /ru/shop/users/1orders/
2024-01-27 15:51:56,900 WARNING django.request: Not Found: /ru/shop/users/45/orders/
2024-01-28 08:44:02,537 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 08:44:22,926 WARNING django.request: Not Found: /
2024-01-28 08:44:32,175 INFO shopapp.views: Rendering shop index
2024-01-28 09:16:33,640 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:16:36,760 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:29:44,618 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:29:48,441 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:32:39,705 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:32:40,831 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:48:12,880 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:48:13,667 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:48:53,301 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:48:54,301 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:48:56,361 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 335, in get
    return JsonResponse(serializer.data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:48:57,978 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 335, in get
    return JsonResponse(serializer.data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:49:58,538 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:49:59,295 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:50:00,259 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 335, in get
    return JsonResponse(serializer)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:50:01,508 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 335, in get
    return JsonResponse(serializer)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:50:03,595 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 335, in get
    return JsonResponse(serializer)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:50:23,376 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:50:23,510 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 335, in get
    return JsonResponse(serializer.data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:50:24,434 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:50:24,940 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 335, in get
    return JsonResponse(serializer.data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:50:25,877 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 335, in get
    return JsonResponse(serializer.data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:50:41,314 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:50:42,359 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:52:48,624 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:52:49,290 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:52:50,185 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'QuerySet' object has no attribute 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 340, in get
    return JsonResponse(serializer.data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/relations.py", line 190, in get_attribute
    return super().get_attribute(instance)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `user` on serializer `OrderSerializer_2`.
The serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.
Original exception text was: 'QuerySet' object has no attribute 'user'.
2024-01-28 09:52:51,352 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'QuerySet' object has no attribute 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 340, in get
    return JsonResponse(serializer.data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/relations.py", line 190, in get_attribute
    return super().get_attribute(instance)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `user` on serializer `OrderSerializer_2`.
The serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.
Original exception text was: 'QuerySet' object has no attribute 'user'.
2024-01-28 09:54:00,852 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:54:01,608 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:54:02,470 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'QuerySet' object has no attribute 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 340, in get
    return JsonResponse(serializer.data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/relations.py", line 190, in get_attribute
    return super().get_attribute(instance)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `user` on serializer `OrderSerializer_2`.
The serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.
Original exception text was: 'QuerySet' object has no attribute 'user'.
2024-01-28 09:55:26,633 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:55:27,307 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:56:01,834 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:56:02,952 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:56:33,503 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:56:34,946 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:56:36,578 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 351, in get
    return JsonResponse(serialized_data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:56:37,828 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 351, in get
    return JsonResponse(serialized_data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:56:39,822 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 351, in get
    return JsonResponse(serialized_data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 09:57:21,356 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:57:22,446 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:58:42,492 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:58:43,852 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:58:55,070 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:58:57,219 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 09:59:36,476 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 09:59:37,393 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 10:02:14,676 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 10:02:15,439 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 10:02:53,873 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 10:02:54,798 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 10:02:56,745 ERROR django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/PycharmProjects/python_django/mysite/shopapp/views.py", line 341, in get
    return JsonResponse(serializer.data)
  File "/home/user/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2024-01-28 10:08:35,441 INFO django.utils.autoreload: /home/user/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2024-01-28 10:08:36,932 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-01-28 10:11:27,598 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-02-01 18:56:38,375 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-02-01 18:56:40,152 WARNING django.request: Not Found: /
2024-02-01 18:56:40,518 WARNING django.request: Not Found: /favicon.ico
2024-02-01 18:56:49,048 INFO shopapp.views: Rendering shop index
2024-02-02 09:06:13,523 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-02-02 09:06:26,290 WARNING django.request: Not Found: /
2024-02-02 09:06:26,671 WARNING django.request: Not Found: /favicon.ico
2024-02-02 09:06:32,576 INFO shopapp.views: Rendering shop index
2024-02-02 13:18:44,424 INFO django.utils.autoreload: Watching for file changes with StatReloader
2024-02-02 23:33:28,167 INFO django.utils.autoreload: Watching for file changes with StatReloader
